automation/urls.py
from django.urls import path

from . import views

app_name = 'automation'
urlpatterns = [
    path('create', views.create, name='create'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index_view, name='index'),
    path(r'signup', views.register, name='signup'),
    path('likes/', views.LikeFormView.as_view(), name='likes'),
    path('comments/', views.CommentFormView.as_view(), name='comments'),
    path('followers/', views.FollowerFormView.as_view(), name='followers'),
    path('form/', views.AccountFormView.as_view()),
]

instabot_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import url

urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('automation/', include('automation.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

automation/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User

# Create your models here.
class Account(models.Model):
    user_name = models.CharField(max_length=150)
    password = models.CharField(max_length=100)
    email = models.CharField(max_length=150)

    def __str__(self):
        return f"{self.user_name}"


class Order(models.Model):
    like_service_purchased = models.BooleanField(default=False)
    comment_service_purchased = models.BooleanField(default=False)
    follower_service_purchased = models.BooleanField(default=False)
    picture_link = models.CharField(max_length=1000)
    number_of_users = models.IntegerField(default=0)
    comment_message = models.CharField(max_length=500)
    amount_of_likes = models.IntegerField(default=0)
    number_of_followers = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    account_link = models.CharField(null=True, max_length=1000)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from automation.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class AccountForm(forms.Form):
    user_name = forms.CharField()
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    def save_form(self):
        print(self.cleaned_data['password'], self.cleaned_data['email'], self.cleaned_data['user_name'])


class LikeForm(forms.Form):
    picture_link = forms.CharField()
    amount_of_likes = forms.CharField(widget=forms.NumberInput)

    def save_form(self, user_id):
        if self.cleaned_data['picture_link'] and self.cleaned_data['amount_of_likes']:
            Order.objects.create(user_id=user_id ,like_service_purchased=True, picture_link=self.cleaned_data['picture_link'], amount_of_likes=self.cleaned_data['amount_of_likes'])
            print(self.cleaned_data['picture_link'], self.cleaned_data['amount_of_likes'])


class CommentForm(forms.Form):
    picture_link = forms.CharField()
    comment_message = forms.CharField(widget=forms.Textarea)
    number_of_users = forms.CharField(widget=forms.NumberInput)


    def save_form(self, user_id):
        if self.cleaned_data['picture_link'] and self.cleaned_data['comment_message'] and self.cleaned_data['number_of_users']:
            Order.objects.create(user_id=user_id, comment_service_purchased=True, picture_link=self.cleaned_data['picture_link'], comment_message=self.cleaned_data['comment_message'], number_of_users=self.cleaned_data['number_of_users'])
            print(self.cleaned_data['picture_link'], self.cleaned_data['comment_message'], self.cleaned_data['number_of_users'])


class FollowerForm(forms.Form):
    account_link = forms.CharField()
    number_of_followers = forms.CharField(widget=forms.NumberInput)

    def save_form(self, user_id):
        if self.cleaned_data['account_link'] and self.cleaned_data['number_of_followers']:
            Order.objects.create(user_id=user_id, follower_service_purchased=True, account_link=self.cleaned_data['account_link'], number_of_followers=self.cleaned_data['number_of_followers'])
            print(self.cleaned_data['account_link'], self.cleaned_data['number_of_followers'])


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

automation/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def create(request):
    print("Hello")
    return HttpResponseRedirect('')

dashboard/views.py
from django.shortcuts import render
from automation.models import *
from django.views import generic
from django.views.generic.edit import FormView
import dashboard
from dashboard.forms import AccountForm, LikeForm, CommentForm, FollowerForm
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
from django.contrib.auth import login
from django.shortcuts import  render, redirect
from django.urls import reverse
import pdb

# Create your views here.
def index_view(request):
    current_user = request.user
    print('current_user', current_user.id)
    return render(request, 'dashboard/index.html')


class LikeFormView(FormView):
    template_name = 'dashboard/like.html'
    form_class = LikeForm
    success_url = '/dashboard/'

    def form_valid(self, form):
        form.save_form(self.request.user.id)
        return super().form_valid(form)

class CommentFormView(FormView):
    template_name = 'dashboard/comment.html'
    form_class = CommentForm
    success_url = '/dashboard/'

    def form_valid(self, form):
        form.save_form(self.request.user.id)
        return super().form_valid(form)


class FollowerFormView(FormView):
    template_name = 'dashboard/follower.html'
    form_class = FollowerForm
    success_url = '/dashboard/'

    def form_valid(self, form):
        form.save_form(self.request.user.id)
        return super().form_valid(form)


class DetailView(generic.DetailView):
    model = Account
    template_name = 'dashboard/detail.html'


class AccountFormView(FormView):
    template_name = 'dashboard/account.html'
    form_class = AccountForm
    success_url = '/dashboard/'

    def form_valid(self, form):
        form.save_form()
        return super().form_valid(form)


def register(request):
    if request.method == "GET":
        return render(
            request, "registration/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("dashboard:index")

dashboard/templates/base.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Django People</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

dashboard/templates/dashboard/account.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group row">
        <label for="user_name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" name="user_name" class="form-control" placeholder="Enter User Name">
        </div>
    </div>
    <div class="form-group row">
        <label for="email" class="col-sm-2 col-form-label">EMAIL:</label>
        <div class="col-sm-10">
            <input type="text" name="email" class="form-control" placeholder="Email">
        </div>
    </div>
    <div class="form-group row">
        <label for="password" class="col-sm-2 col-form-label">Password:</label>
        <div class="col-sm-10">
            <input type="text" name="password" class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>

dashboard/templates/dashboard/comment.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/form.css' %}">

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group row">
            <label for="picture_link" class="col-sm-2 col-form-label">Insert Picture Link:</label>
            <div class="col-sm-10">
                <input type="text" name="picture_link" class="form-control" placeholder="Insert URL">
            </div>
        </div>
        <div class="form-group row">
            <label for="comment_message" class="col-sm-2 col-form-label">Comment Message:</label>
            <div class="col-sm-10">
                <input type="text" name="comment_message" class="form-control" placeholder="Enter Message">
            </div>
        </div>
        <div class="form-group row">
            <label for="number_of_users" class="col-sm-2 col-form-label">Enter Number Of users for Commenting</label>
            <div class="col-sm-10">
                <input type="number" name="number_of_users" class="form-control" placeholder="Enter Number of User">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10 offset-sm-2">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
</div>

dashboard/templates/dashboard/detail.html
{{account}}

dashboard/templates/dashboard/follower.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/form.css' %}">

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group row">
        <label for="account_link" class="col-sm-2 col-form-label">Insert Account Link:</label>
        <div class="col-sm-10">
            <input type="text" name="account_link" class="form-control" placeholder="Insert URL">
        </div>
    </div>
    <div class="form-group row">
        <label for="number_of_followers" class="col-sm-2 col-form-label">Number of followers:</label>
        <div class="col-sm-10">
            <input type="number" name="number_of_followers" class="form-control" placeholder="Enter Number of followers">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
    </form>
</div>

dashboard/templates/dashboard/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/styles.css' %}">

{% block logout %}
  {% include 'dashboard/logout.html' %}
{% endblock %}

Hello, {{ user.username | default:'Guest' }}!
<div class="url-containers">
  <a href="{% url 'dashboard:likes' %}">BUY LIKES</a>
  <a href="{% url 'dashboard:comments' %}">BUY COMMENTS</a>
  <a href="{% url 'dashboard:followers' %}">BUY FOLLOWERS</a>
</div>

dashboard/templates/dashboard/like.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/form.css' %}">

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group row">
        <label for="picture_link" class="col-sm-2 col-form-label">Insert Picture Link:</label>
        <div class="col-sm-10">
            <input type="text" name="picture_link" class="form-control" placeholder="Insert URL">
        </div>
    </div>
    <div class="form-group row">
        <label for="amount_of_likes" class="col-sm-2 col-form-label">Number of likes:</label>
        <div class="col-sm-10">
            <input type="number" name="amount_of_likes" class="form-control" placeholder="Enter Number of Likes">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
    </form>
</div>

dashboard/templates/dashboard/logout.html
{% block content %}
<div class="logout-container float-right">
  {% if user.is_authenticated %}
    <a href="{% url 'logout' %}">LOGOUT</a>
  {% else %}
    <a href="{% url 'login' %}">LOGIN</a>
  {% endif %}
<a href="{% url 'dashboard:signup' %}">SIGNUP</a>
</div>
{% endblock %}